### ISSUE TITLE
Erro em 18/02/2020

### ISSUE THREAD

**Issue by Ceagah** [RenanRB/curso-angular#1]
Bom dia Renan ! 
Estou com problemas para utilizar o seu projeto.
Está dando um erro, pois na data que eu estou fazendo o curso, o angular foi atualizado, e quando eu clono o projeto e tento dar um ng serve , ele da erro "An unhandled exception occurred: context.getProjectMetadata is not a function
See "/tmp/ng-1BaWT8/angular-errors.log" for further details."
Ja busquei esse erro no google e nao consegui arruma-lo.

**Comment by evertondg** [comment]
@Ceagah tudo bem!?  vamos lá. 
de uma olhada aqui 
https://update.angular.io/#8.0:9.0  creio que vai conseguir atualizar

**Comment by RenanRB** [comment]
Olá @Ceagah , desculpe a demora, caso ainde esta com problemas pode entrar em contato
